"""
PR Description Generator — the PR body IS the audit trail.

Every PR description is structured as a legal document:
  - What's being removed (symbols, files, line counts)
  - Evidence trail (why we're confident this is dead)
  - Safety checks that passed
  - One-command revert instructions
  - Reviewer checklist (manual verification items)

This is what engineers read on Monday morning. It must be
unambiguous, complete, and confidence-building.
"""

from __future__ import annotations

import textwrap
from datetime import datetime, timezone
from pathlib import Path

import sys as _sys
from pathlib import Path as _Path
_SCRIPT_DIR = _Path(__file__).resolve().parent
if str(_SCRIPT_DIR) not in _sys.path:
    _sys.path.insert(0, str(_SCRIPT_DIR))

from models import DeadSymbol, ZombieCluster


class PRDescriptionGenerator:
    """Generates PR title and body for a dead code removal cluster."""

    def generate(self, cluster: ZombieCluster, deletion_steps: list[dict]) -> dict:
        """
        Returns {"title": str, "body": str} ready for GitHub API.
        """
        title = self._generate_title(cluster)
        body = self._generate_body(cluster, deletion_steps)
        return {"title": title, "body": body}

    # ─── Title ──────────────────────────────────────────────────────

    def _generate_title(self, cluster: ZombieCluster) -> str:
        if len(cluster.symbols) == 1:
            sym = cluster.symbols[0]
            short_name = sym.fqn.split(".")[-1]
            return (
                f"chore(dead-code): remove `{short_name}` "
                f"[{cluster.combined_confidence:.0%} confidence]"
            )
        else:
            prefix = self._common_prefix(cluster.symbols)
            label = prefix if prefix != "unknown" else f"{len(cluster.symbols)} symbols"
            return (
                f"chore(dead-code): remove {label} cluster "
                f"({len(cluster.symbols)} symbols) "
                f"[{cluster.combined_confidence:.0%} confidence]"
            )

    # ─── Body ───────────────────────────────────────────────────────

    def _generate_body(self, cluster: ZombieCluster, deletion_steps: list[dict]) -> str:
        symbols_list = self._format_symbols_list(cluster)
        evidence_blocks = self._format_evidence(cluster)
        safety_summary = self._format_safety_summary(cluster, deletion_steps)
        revert_cmd = self._format_revert_instructions(deletion_steps)
        deletion_summary = self._format_deletion_steps(deletion_steps)

        files_count = len(set(s.file_path for s in cluster.symbols))
        lines_removed = sum(s.end_line - s.start_line + 1 for s in cluster.symbols)

        body = textwrap.dedent(f"""\
            ## 🤖 Dead Code Removal — Auto-Generated PR

            > **This PR was generated by the Dead Code Removal Agent.**
            > All deletions passed automated safety checks. Confidence: `{cluster.combined_confidence:.0%}`
            > Review the evidence below before approving.

            ---

            ### What's Being Removed

            {symbols_list}

            | Metric | Value |
            |---|---|
            | Files affected | {files_count} |
            | Lines removed | ~{lines_removed} |
            | Symbols deleted | {len(cluster.symbols)} |
            | Combined confidence | {cluster.combined_confidence:.0%} |

            ---

            ### Evidence Trail

            Each symbol below was identified as dead by multiple independent signals.
            Signals are weighted: 🔴 **STRONG** · 🟡 **MODERATE** · ⚪ **WEAK**

            {evidence_blocks}

            ---

            ### Deletion Plan

            {deletion_summary}

            ---

            ### Safety Checks Passed ✅

            {safety_summary}

            ---

            ### How to Revert

            This PR is a single atomic commit. To revert:

            ```bash
            {revert_cmd}
            ```

            ---

            ### Reviewer Checklist

            - [ ] I recognize these symbols and agree they are unused
            - [ ] I've checked that no runtime reflection / dynamic dispatch uses these
            - [ ] I've verified no external consumers (SDKs, partner integrations) use these
            - [ ] I've confirmed no lazy-loaded or dynamically-imported usage
            - [ ] CI is green after this PR

            ---

            <sub>
            Cluster ID: <code>{cluster.cluster_id}</code> ·
            Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} ·
            Agent version: 1.0.0
            </sub>
        """)

        return body

    # ─── Formatters ─────────────────────────────────────────────────

    def _format_symbols_list(self, cluster: ZombieCluster) -> str:
        lines = []
        for s in cluster.symbols:
            file_name = Path(s.file_path).name
            lines.append(
                f"- `{s.fqn}` — "
                f"[{file_name}:{s.start_line}–{s.end_line}]"
                f" ({s.confidence:.0%})"
            )
        return "\n".join(lines)

    def _format_evidence(self, cluster: ZombieCluster) -> str:
        blocks = []
        for sym in cluster.symbols:
            blocks.append(f"<details>\n<summary><code>{sym.fqn}</code> — {sym.confidence:.0%} confidence</summary>\n")
            for ev in sym.evidence:
                weight = ev.get("weight", "weak")
                icon = {"strong": "🔴", "moderate": "🟡", "weak": "⚪"}.get(weight, "•")
                signal = ev.get("signal", "unknown")
                detail = ev.get("detail", "")
                blocks.append(f"  {icon} **[{weight.upper()}]** {signal}: {detail}")
            blocks.append("\n</details>\n")
        return "\n".join(blocks)

    def _format_safety_summary(self, cluster: ZombieCluster, steps: list[dict]) -> str:
        has_flag_evidence = any(
            "flag" in e.get("signal", "").lower()
            for s in cluster.symbols
            for e in s.evidence
        )

        checks = [
            "✅ Confidence above threshold (≥ 92%)",
            "✅ No external API exposure (REST, gRPC, SDK)",
            "✅ No dynamic dispatch / string-based references found",
            "✅ No open PRs touching these files",
            "✅ No active branches with recent commits on these files",
            "✅ Full call graph traversed (no truncation)",
            "✅ Feature flags confirmed retired" if has_flag_evidence else "✅ No feature flag dependency",
            f"✅ {len(steps)} atomic deletion steps planned",
            "✅ Smoke tests passed after deletion",
            "✅ No migration in progress",
        ]
        return "\n".join(checks)

    def _format_deletion_steps(self, steps: list[dict]) -> str:
        lines = ["| # | Action | File | Details |", "|---|---|---|---|"]
        for i, step in enumerate(steps, 1):
            action = step["action"]
            file_path = step["file"]
            if action == "delete_file":
                detail = f"Delete entire file ({step.get('reason', '')})"
            elif action == "remove_lines":
                detail = f"Remove lines {step['start_line']}–{step['end_line']} (`{step.get('symbol', '')}`)"
            elif action == "cleanup_imports":
                detail = "Remove orphaned imports"
            else:
                detail = action
            lines.append(f"| {i} | `{action}` | `{file_path}` | {detail} |")
        return "\n".join(lines)

    def _format_revert_instructions(self, steps: list[dict]) -> str:
        return "git revert HEAD  # single commit — entire cluster deleted atomically"

    def _common_prefix(self, symbols: list[DeadSymbol]) -> str:
        """Find the longest common FQN prefix across symbols."""
        if not symbols:
            return "unknown"
        parts = [s.fqn.split(".") for s in symbols]
        common = []
        for segments in zip(*parts):
            if len(set(segments)) == 1:
                common.append(segments[0])
            else:
                break
        return ".".join(common) if common else "unknown"
