"""
Scoring — deterministic confidence calculation from evidence signals.

Core principle: confidence is COMPUTED from tool outputs, never GENERATED by an LLM.

Each evidence signal has a weight (strong/moderate/weak) and contributes
to the combined confidence score via a weighted formula. The LLM can only
produce weak signals — strong signals come exclusively from deterministic tools.

Signal Categories:
  - Graph signals:    Reference count, SCC isolation, import orphan status
  - Temporal signals: Last modified date, commit frequency
  - Static signals:   Grep reference count, test coverage
  - LLM signals:      Adversarial assessment (always weak weight)
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Optional

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────
# Evidence Weights
# ─────────────────────────────────────────────

class EvidenceWeight:
    """Weight enum — constrained to prevent LLM from inventing weights."""
    STRONG = "strong"       # Tool-verified, deterministic
    MODERATE = "moderate"   # Tool-sourced but heuristic
    WEAK = "weak"           # LLM-generated or uncertain

    # Numerical values for scoring
    VALUES = {
        "strong": 0.30,
        "moderate": 0.15,
        "weak": 0.05,
    }

    @classmethod
    def value(cls, weight: str) -> float:
        return cls.VALUES.get(weight, 0.0)


# ─────────────────────────────────────────────
# Evidence Generators (Tool-sourced signals)
# ─────────────────────────────────────────────

def evidence_zero_references(grep_count: int, total_files: int) -> dict:
    """Signal: ripgrep found zero references to this symbol."""
    return {
        "signal": "zero_references",
        "detail": f"ripgrep found {grep_count} matches across {total_files:,} files",
        "weight": EvidenceWeight.STRONG if grep_count == 0 else EvidenceWeight.WEAK,
        "source": "ripgrep",
    }


def evidence_scc_isolated(scc_size: int, inbound_from_alive: int) -> dict:
    """Signal: symbol is in an SCC with zero inbound edges from alive code."""
    return {
        "signal": "scc_isolated",
        "detail": (
            f"In SCC of {scc_size} node(s) with {inbound_from_alive} "
            f"inbound edge(s) from alive code"
        ),
        "weight": EvidenceWeight.STRONG if inbound_from_alive == 0 else EvidenceWeight.MODERATE,
        "source": "graph_traversal",
    }


def evidence_git_stale(last_modified: str, days_stale: int) -> dict:
    """Signal: symbol hasn't been modified in a long time."""
    if days_stale > 365:
        weight = EvidenceWeight.STRONG
    elif days_stale > 180:
        weight = EvidenceWeight.MODERATE
    else:
        weight = EvidenceWeight.WEAK
    return {
        "signal": "git_stale",
        "detail": f"Last modified {last_modified} ({days_stale} days ago)",
        "weight": weight,
        "source": "git_blame",
    }


def evidence_no_test_coverage(has_tests: bool, test_files_checked: int) -> dict:
    """Signal: no test file references this symbol."""
    return {
        "signal": "no_test_coverage",
        "detail": (
            f"No test references found across {test_files_checked} test files"
            if not has_tests
            else "Test references found"
        ),
        "weight": EvidenceWeight.MODERATE if not has_tests else EvidenceWeight.WEAK,
        "source": "test_scanner",
    }


def evidence_import_orphan(import_count: int) -> dict:
    """Signal: symbol is imported by zero other modules."""
    return {
        "signal": "import_orphan",
        "detail": f"Imported by {import_count} module(s)",
        "weight": EvidenceWeight.STRONG if import_count == 0 else EvidenceWeight.WEAK,
        "source": "import_graph",
    }


def evidence_feature_flag_retired(flag_name: str, is_retired: bool) -> dict:
    """Signal: associated feature flag is retired/disabled."""
    if is_retired:
        return {
            "signal": "feature_flag_retired",
            "detail": f"Feature flag '{flag_name}' is retired/permanently disabled",
            "weight": EvidenceWeight.STRONG,
            "source": "launchdarkly_api",
        }
    return {
        "signal": "feature_flag_active",
        "detail": f"Feature flag '{flag_name}' is still active",
        "weight": EvidenceWeight.STRONG,  # Active flag = strong evidence it's ALIVE
        "source": "launchdarkly_api",
    }


def evidence_llm_assessment(reasoning: str, alive_mechanisms_found: int) -> dict:
    """
    Signal: LLM adversarial assessment.
    ALWAYS weak weight — LLMs don't get to have strong opinions about liveness.
    """
    return {
        "signal": "llm_adversarial_review",
        "detail": reasoning[:200],  # Truncate to prevent bloat
        "weight": EvidenceWeight.WEAK,
        "source": "llm_judge",
        "alive_mechanisms": alive_mechanisms_found,
    }


# ─────────────────────────────────────────────
# Confidence Calculator
# ─────────────────────────────────────────────

@dataclass
class ScoringConfig:
    """Tunable scoring parameters."""
    # Maximum possible score (normalizer)
    # With 5 strong signals: 5 * 0.30 = 1.50 → normalized to 1.0
    max_score: float = 1.50

    # Penalty per "alive mechanism" found by LLM
    alive_penalty: float = 0.15

    # Minimum evidence signals required
    min_signals: int = 2

    # Floor: never report confidence below this (avoid false precision)
    confidence_floor: float = 0.0

    # Ceiling: never report above this (100% is arrogant)
    confidence_ceiling: float = 0.99


def calculate_confidence(
    evidence: list[dict],
    config: Optional[ScoringConfig] = None,
) -> float:
    """
    Calculate combined confidence score from a list of evidence signals.

    The formula:
      raw_score = sum(weight_value for each signal that supports "dead")
                  - penalty for each alive mechanism found
      confidence = clamp(raw_score / max_score, floor, ceiling)

    Returns a float between 0.0 and 0.99.
    """
    if config is None:
        config = ScoringConfig()

    if len(evidence) < config.min_signals:
        logger.debug("Not enough evidence signals (%d < %d)", len(evidence), config.min_signals)
        return config.confidence_floor

    raw_score = 0.0
    alive_mechanisms = 0

    for e in evidence:
        weight = e.get("weight", "weak")
        signal = e.get("signal", "")

        # Feature flag ACTIVE is evidence of life, not death
        if signal == "feature_flag_active":
            raw_score -= EvidenceWeight.value(weight)
            continue

        # LLM signals: check for alive mechanisms
        if signal == "llm_adversarial_review":
            alive_mechanisms += e.get("alive_mechanisms", 0)

        # Add positive evidence
        raw_score += EvidenceWeight.value(weight)

    # Apply alive mechanism penalty
    raw_score -= alive_mechanisms * config.alive_penalty

    # Normalize to [0, 1]
    normalized = raw_score / config.max_score

    # Clamp
    return max(config.confidence_floor, min(config.confidence_ceiling, normalized))


def calculate_cluster_confidence(
    symbol_confidences: list[float],
    strategy: str = "min",
) -> float:
    """
    Calculate cluster-level confidence from individual symbol scores.

    Strategies:
      - "min":  Use the minimum (most conservative — one weak link blocks the PR)
      - "avg":  Use the average
      - "p25":  Use the 25th percentile
    """
    if not symbol_confidences:
        return 0.0

    sorted_scores = sorted(symbol_confidences)

    if strategy == "min":
        return sorted_scores[0]
    elif strategy == "avg":
        return sum(sorted_scores) / len(sorted_scores)
    elif strategy == "p25":
        idx = max(0, int(len(sorted_scores) * 0.25))
        return sorted_scores[idx]
    else:
        return sorted_scores[0]  # Default to min (safest)
